# Website Basic Information
baseURL = "https://bloguz.athenalarm.com/"    # Placeholder URL, change to Cloudflare Pages URL after deployment
title = "Athenalarm Blogi"
languageCode = "uz"
theme = "ananke"

# Author Information (optional)
[author]
  name = "Athenalarm"
  email = "info@athenalarm.com"

# Website Menu (optional)
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Bosh sahifa"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "posts"
    name = "Maqolalar"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    identifier = "contact"
    name = "Bog‘lanish"
    url = "/contact/"
    weight = 3

# ---------------------------
# Home Page Settings
# ---------------------------
paginate = 5          # Bosh sahifada oxirgi 5 ta maqola ko‘rsatiladi
mainSections = ["posts"]  # Bosh sahifa faqat "posts" turidagi maqolalarni ko‘rsatadi