# Website Basic Information
baseURL = "https://blogtl.athenalarm.com/"    # Placeholder URL, change to Cloudflare Pages URL after deployment
title = "Blog ng Athenalarm"
languageCode = "tl"
theme = "ananke"

# Author Information (optional)
[author]
  name = "Athenalarm"
  email = "info@athenalarm.com"

# Website Menu (optional)
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Bahay"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "posts"
    name = "Mga Post"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    identifier = "contact"
    name = "Makipag-ugnay"
    url = "/contact/"
    weight = 3

# ---------------------------
# Home Page Settings
# ---------------------------
paginate = 5          # Homepage shows latest 5 posts
mainSections = ["posts"]  # Home page only shows articles of type "posts"